from . import db


class PartyDetail(db.Model):
    __tablename__ = 'partydetail'

    def __init__(self):
        pass

    sr_no = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Code = db.Column(db.Integer, nullable=True)
    Vcode = db.Column(db.Integer, nullable=True)
    Lgr_Id = db.Column(db.Integer, nullable=True)
    Agent_Id = db.Column(db.Integer, nullable=True)
    Transport_Id = db.Column(db.Integer, nullable=True)
    Bill_No = db.Column(db.Unicode(255), nullable=True)
    JobFlag = db.Column(db.Unicode(255), nullable=True)
    Dates = db.Column(db.DateTime, nullable=True)
    Bill_Amount = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Rec_Amount = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Discount = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OtherLess = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Pending_Amount = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Interest = db.Column(db.Float(precision=10, decimal_return_scale=2))
    InterestRec = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Commission = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Days = db.Column(db.Integer, nullable=True)
    LrNo = db.Column(db.Unicode(255), nullable=True)
    LrDate = db.Column(db.DateTime, nullable=True)
    ItemName = db.Column(db.Unicode(255), nullable=True)
    ItemDetail = db.Column(db.Unicode(255), nullable=True)
    Setteled = db.Column(db.Boolean, nullable=True)
    Cmp_Code = db.Column(db.Integer, nullable=True)
    Paid = db.Column(db.Boolean, nullable=True)
    Net_Snet = db.Column(db.Unicode(255), nullable=True)
    DnMade = db.Column(db.Integer, nullable=True)
    CRDAYS = db.Column(db.Integer, nullable=True)
    SALES_ORDERNO = db.Column(db.Unicode(255), nullable=True)
    SALES_ORDER_DATE = db.Column(db.DateTime, nullable=True)
    SALES_CONFNO = db.Column(db.Unicode(255), nullable=True)
    SALES_CONF_DATE = db.Column(db.DateTime, nullable=True)
    ADD_DATE = db.Column(db.DateTime, nullable=True)
    EDIT_DATE = db.Column(db.DateTime, nullable=True)
    USERID = db.Column(db.Integer, nullable=True)
    STATION_ID = db.Column(db.Boolean, nullable=True)
    INUSED = db.Column(db.Boolean, nullable=True)
    Sal_Reb_Per = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Reb_Less = db.Column(db.Boolean, nullable=True)
    Sal_Insurance = db.Column(db.Boolean, nullable=True)
    sal_discper = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_RateDiffAmt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_InsuranceAmt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Reb_Amt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SchemeAmt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    NETRATEAMOUNT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_NetRateDiffAmt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    BROK_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER_DISC = db.Column(db.Float(precision=10, decimal_return_scale=2))
    INT_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    DEBIT_AMT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    CREDIT_AMT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    LRCANSENT = db.Column(db.Boolean, nullable=True)
    DOCUMENTS = db.Column(db.Unicode(255), nullable=True)
    BALES = db.Column(db.Integer, nullable=True)
    ADJ_OTHER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    ADJ_INTEREST = db.Column(db.Float(precision=10, decimal_return_scale=2))
    TOTALTAXABLEVALUE = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SALES_ALIAS = db.Column(db.Unicode(255), nullable=True)
    DEPARTMENT_ID = db.Column(db.Integer, nullable=True)
