from . import db


class ConsigneeMaster(db.Model):
    __tablename__ = 'consigneemaster'

    def __init__(self):
        pass

    Consignee_Id = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.Unicode(255), nullable=True)
    Add1 = db.Column(db.Unicode(255), nullable=True)
    Add2 = db.Column(db.Unicode(255), nullable=True)
    Add3 = db.Column(db.Unicode(255), nullable=True)
    City_Id = db.Column(db.Integer, nullable=True)
    Pincode = db.Column(db.Unicode(255), nullable=True)
    State_Id = db.Column(db.Integer, nullable=True)
    Country = db.Column(db.Unicode(255), nullable=True)
    GSTINNO = db.Column(db.Unicode(255), nullable=True)
    EMAIL = db.Column(db.Unicode(255), nullable=True)
    PhoneNo = db.Column(db.Unicode(255), nullable=True)
    MobileNo = db.Column(db.Unicode(255), nullable=True)
    LEGALNAME = db.Column(db.Unicode(255), nullable=True)

    # salesorder = db.relationship('SalesOrder', backref='consigneemaster', lazy=True)
    # salesinvoice = db.relationship('SalesInvoice', backref='consigneemaster', lazy=True)


class HasteMaster(db.Model):
    __tablename__ = 'hastemaster'

    def __init__(self):
        pass

    HASTE_ID = db.Column(db.Integer, primary_key=True)
    HASTE_NAME = db.Column(db.Unicode(255), nullable=True)
    Add_Date = db.Column(db.DateTime, nullable=False)
    Edit_Date = db.Column(db.DateTime, nullable=True)
    UserId = db.Column(db.Integer, nullable=True)
    # salesorder = db.relationship('SalesOrder', backref='hastemaster', lazy=True)


class SalesOrder(db.Model):
    __tablename__ = 'salesorder'

    def __init__(self):
        pass

    Sal_Order_Id = db.Column(db.Integer, primary_key=True)
    ConfNo = db.Column(db.Integer, primary_key=True)
    Sales_OrderNo = db.Column(db.Unicode(255), nullable=True)
    Station_Id = db.Column(db.Integer, nullable=True)
    Through = db.Column(db.Unicode(255), nullable=True)
    vch_Date = db.Column(db.DateTime, nullable=True)
    Order_Date = db.Column(db.DateTime, nullable=True)
    Start_Date = db.Column(db.DateTime, nullable=True)
    End_Date = db.Column(db.DateTime, nullable=True)
    Disc = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Scheme = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Scheme_Per = db.Column(db.Unicode(255), nullable=True)
    CrDays = db.Column(db.Integer, nullable=True)
    Total_Bales = db.Column(db.Integer, nullable=True)
    Narration1 = db.Column(db.Unicode(255), nullable=True)
    Narration2 = db.Column(db.Unicode(255), nullable=True)
    TotalBales = db.Column(db.Integer, nullable=True)
    Stop_Date = db.Column(db.DateTime, nullable=True)
    Stop_Reason = db.Column(db.Unicode(255), nullable=True)
    Stop = db.Column(db.Boolean, nullable=True)
    Colours = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Fyear = db.Column(db.Unicode(255), nullable=True)
    Net_Snet = db.Column(db.Unicode(255), nullable=True)
    ADD_DATE = db.Column(db.DateTime, nullable=True)
    EDIT_DATE = db.Column(db.DateTime, nullable=True)
    FLAG = db.Column(db.Integer, nullable=True)
    TotalQty = db.Column(db.Integer, nullable=True)
    price_id = db.Column(db.Integer, nullable=True)
    ORDER_TYPE = db.Column(db.Unicode(255), nullable=True)
    CUST_GRP_ID = db.Column(db.Integer, nullable=True)
    SAL_REB_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SAL_REB_LESS = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SAL_INSURANCE = db.Column(db.Float(precision=10, decimal_return_scale=2))
    BROK_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    LGR_CASH_DISC = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER_DISC = db.Column(db.Float(precision=10, decimal_return_scale=2))
    INT_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SELF_PARTY = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    CashDiscInBill = db.Column(db.Float(precision=10, decimal_return_scale=2))
    isconsignee = db.Column(db.Boolean, nullable=True)
    SERIES_ID = db.Column(db.Integer, nullable=True)
    Lgr_Id = db.Column(db.Integer, nullable=True)
    Agent_Id = db.Column(db.Integer, nullable=True)
    Transport_Id = db.Column(db.Integer, nullable=True)
    consignee_id = db.Column(db.Integer, nullable=True)
    HASTE_ID = db.Column(db.Integer, nullable=True)
    USERID = db.Column(db.Integer, nullable=True)
    Cmp_Code = db.Column(db.Integer, nullable=True)
    # salesinvoicedetail = db.relationship('SalesInvoiceDetail', backref='salesorder', lazy=True)
    # salesorderdetail = db.relationship('SalesOrderDetail', backref='salesorder', lazy=True)

    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}


class SalesOrderDetail(db.Model):
    __tablename__ = 'salesorderdetail'

    def __init__(self):
        pass

    sr_no = db.Column(db.Integer, primary_key=True, autoincrement=True)

    SrNo = db.Column(db.Integer, nullable=True)

    Item_Cut = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Bales = db.Column(db.Integer, nullable=True)
    PendingBales = db.Column(db.Integer, nullable=True)
    DeliveredBales = db.Column(db.Integer, nullable=True)
    Pieces = db.Column(db.Float(precision=10, decimal_return_scale=2))
    PendingPieces = db.Column(db.Float(precision=10, decimal_return_scale=2))
    DeliveredPieces = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Meter = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Rate = db.Column(db.Float(precision=10, decimal_return_scale=2))
    RateDiff = db.Column(db.Integer, nullable=True)
    Net_Snet = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Remark = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Cmp_Code = db.Column(db.Integer, nullable=True)
    ASSORT = db.Column(db.Integer, nullable=True)
    Assort_Delivered = db.Column(db.Integer, nullable=True)
    Assort_Pending = db.Column(db.Integer, nullable=True)
    Cancel = db.Column(db.Boolean, nullable=True)
    AssortMent_YN = db.Column(db.Unicode(255), nullable=True)
    Fyear = db.Column(db.Unicode(255), nullable=True)
    COLOR_CHART = db.Column(db.Integer, nullable=True)
    PACKINGSTYLE_ID = db.Column(db.Integer, nullable=True)
    FLAG = db.Column(db.Boolean, nullable=True)
    Weaver_Id = db.Column(db.Integer, nullable=True)
    Quantity = db.Column(db.Integer, nullable=True)
    DeliveredQty = db.Column(db.Float(precision=10, decimal_return_scale=2))
    PendingQty = db.Column(db.Float(precision=10, decimal_return_scale=2))
    BalesPcsMtr = db.Column(db.Unicode(255), nullable=True)
    Schedule = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SchQuantity = db.Column(db.Float(precision=10, decimal_return_scale=2))
    FoldPendingBales = db.Column(db.Integer, nullable=True)
    FoldRecBales = db.Column(db.Integer, nullable=True)
    NETRATE = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Item_Id = db.Column(db.Integer, nullable=True)
    Unit_Id = db.Column(db.Integer, nullable=True)
    Sal_Order_Id = db.Column(db.Integer, nullable=True)
    Screen_Id = db.Column(db.Integer, nullable=True)


class SalesInvoice(db.Model):
    __tablename__ = 'salesinvoice'

    def __init__(self):
        pass

    Sal_Inv_Id = db.Column(db.Integer, primary_key=True)
    Sal_Inv_Bill_No = db.Column(db.Integer, nullable=True)
    Sal_Inv_Vdate = db.Column(db.DateTime, nullable=True)

    Station_Id = db.Column(db.Integer, nullable=True)
    Sal_AccID = db.Column(db.Integer, nullable=True)
    ConfNo = db.Column(db.Integer, nullable=True)
    ConfDate = db.Column(db.DateTime, nullable=True)
    OrderNo = db.Column(db.Integer, nullable=True)
    OrderDate = db.Column(db.DateTime, nullable=True)

    Sal_Inv_LrNo = db.Column(db.Integer, nullable=True)
    Sal_Inv_LrDate = db.Column(db.DateTime, nullable=True)
    Sal_Inv_Commission = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Documents = db.Column(db.Unicode(255), nullable=True)
    Sal_Inv_Days = db.Column(db.Integer, nullable=True)
    Sal_Inv_Add1 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add2 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add3 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add4 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add5 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_AddTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less1 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less2 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less3 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less4 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less5 = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_LessTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_RoundOff = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_GrossTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_NetTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_QuantityTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_PcsTotal = db.Column(db.Integer, nullable=True)
    Sal_Inv_BalesTotal = db.Column(db.Integer, nullable=True)
    PAID = db.Column(db.Unicode(255), nullable=True)
    PAID_DATE = db.Column(db.DateTime, nullable=True)
    CHEQUENO = db.Column(db.Unicode(255), nullable=True)
    Lgr_Bank = db.Column(db.Unicode(255), nullable=True)
    Lgr_Branch = db.Column(db.Unicode(255), nullable=True)
    Lgr_Post = db.Column(db.Unicode(255), nullable=True)
    Our_Bank = db.Column(db.Unicode(255), nullable=True)
    Our_Branch = db.Column(db.Unicode(255), nullable=True)
    Our_Post = db.Column(db.Unicode(255), nullable=True)
    Sal_Inv_Add1_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add2_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add3_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add4_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Add5_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less1_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less2_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less3_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less4_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Less5_Set = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Freight = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Weight = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_TpTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_HundiNo = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Fyear = db.Column(db.Unicode(255), nullable=True)
    InSured = db.Column(db.Boolean, nullable=True)
    In_Outer_State = db.Column(db.Unicode(255), nullable=True)
    JOBNO = db.Column(db.Integer, nullable=True)
    Net_Snet = db.Column(db.Unicode(255), nullable=True)
    Flag = db.Column(db.Integer, nullable=True)
    Party_Agent = db.Column(db.Unicode(255), nullable=True)

    SalInvFlag = db.Column(db.Integer, nullable=True)
    OtherCmp = db.Column(db.Integer, nullable=True)
    Sal_Remark = db.Column(db.Unicode(255), nullable=True)
    Sal_CrDays = db.Column(db.Integer, nullable=True)
    ADD_DATE = db.Column(db.DateTime, nullable=True)
    EDIT_DATE = db.Column(db.DateTime, nullable=True)
    USERID = db.Column(db.Integer, nullable=True)
    SENT_PARTY = db.Column(db.Boolean, nullable=True)
    SENT_AGENT = db.Column(db.Boolean, nullable=True)
    SERIES_ID = db.Column(db.Integer, nullable=True)
    Sal_Inv_NetQuantityTotal = db.Column(db.Integer, nullable=True)
    Sal_Inv_Type = db.Column(db.Unicode(255), nullable=True)
    AfterLessTotal = db.Column(db.Float(precision=10, decimal_return_scale=2))
    RecDate = db.Column(db.DateTime, nullable=True)
    SAMPLE = db.Column(db.Boolean, nullable=True)
    GIFT = db.Column(db.Boolean, nullable=True)
    Sal_Inv_AdDate = db.Column(db.DateTime, nullable=True)
    REC_CHECK = db.Column(db.Boolean, nullable=True)
    CUST_GRP_ID = db.Column(db.Integer, nullable=True)
    Amt_Word = db.Column(db.Unicode(255), nullable=True)
    WIPSALE = db.Column(db.Boolean, nullable=True)
    Sal_Reb_Per = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Reb_Less = db.Column(db.Boolean, nullable=True)
    Sal_Insurance = db.Column(db.Boolean, nullable=True)
    sal_discper = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_RateDiffAmt = db.Column(db.Float(precision=10, decimal_return_scale=2))
    NETRATEAMOUNT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    BROK_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SAL_INV_BALENO = db.Column(db.Integer, nullable=True)
    OTHER_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    OTHER_DISC = db.Column(db.Float(precision=10, decimal_return_scale=2))
    INT_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    PARTY_MAIL_SENT = db.Column(db.Unicode(255), nullable=True)
    AGENT_MAIL_SENT = db.Column(db.Unicode(255), nullable=True)
    Type_id = db.Column(db.Integer, nullable=True)
    party_statecode = db.Column(db.Unicode(255), nullable=True)

    IsConsignee = db.Column(db.Boolean, nullable=True)
    shipdate = db.Column(db.DateTime, nullable=True)
    shipbillno = db.Column(db.Integer, nullable=True)
    exporttype = db.Column(db.Unicode(255), nullable=True)
    port = db.Column(db.Unicode(255), nullable=True)
    ewaybillno = db.Column(db.Unicode(255), nullable=True)
    VEHICLENO = db.Column(db.Unicode(255), nullable=True)
    EWB_DATE = db.Column(db.DateTime, nullable=True)
    SALES_ALIAS = db.Column(db.Unicode(255), nullable=True)
    RevisedInvoiceNo = db.Column(db.Unicode(255), nullable=True)
    RevisedInvoiceDate = db.Column(db.DateTime, nullable=True)
    AmendmentDate = db.Column(db.DateTime, nullable=True)
    PHYSICAL = db.Column(db.Boolean, nullable=True)
    REFUNDAMT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    REFUNDDATE = db.Column(db.DateTime, nullable=True)
    EINVNO = db.Column(db.Unicode(255), nullable=True)
    TCS_PER = db.Column(db.Float(precision=10, decimal_return_scale=2))
    TCS_AMT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    EXP_LCNO = db.Column(db.Unicode(255), nullable=True)
    EXP_CR_NO = db.Column(db.Unicode(255), nullable=True)
    EXP_DOC_CR_DATE = db.Column(db.DateTime, nullable=True)
    EXP_ISS_BANK = db.Column(db.Unicode(255), nullable=True)
    EXP_DRW_BANK = db.Column(db.Unicode(255), nullable=True)
    EXP_CUST_OFF = db.Column(db.Unicode(255), nullable=True)
    EXP_PERF_NO = db.Column(db.Unicode(255), nullable=True)
    EXP_PERF_DATE = db.Column(db.DateTime, nullable=True)
    EXP_TOT_SQR = db.Column(db.Float(precision=10, decimal_return_scale=2))
    EXP_GRS_WT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    EXP_NET_WT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    EXP_LUTARNO = db.Column(db.Unicode(255), nullable=True)
    EXP_SAFTA_REF_NO = db.Column(db.Unicode(255), nullable=True)
    EXP_SAFTA_DATE = db.Column(db.DateTime, nullable=True)
    EXP_TERM1 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM2 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM3 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM4 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM5 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM6 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM7 = db.Column(db.Unicode(255), nullable=True)
    EXP_TERM8 = db.Column(db.Unicode(255), nullable=True)
    DEPARTMENT_ID = db.Column(db.Integer, nullable=True)
    IRN = db.Column(db.Unicode(255), nullable=True)
    ACK_DATE = db.Column(db.DateTime, nullable=True)
    SIGNED_QR_CODE = db.Column(db.LargeBinary, nullable=True)
    Consignee_Id = db.Column(db.Integer, nullable=True)
    Lgr_Id = db.Column(db.Integer, nullable=True)
    Agent_Id = db.Column(db.Integer, nullable=True)
    Transport_Id = db.Column(db.Integer, nullable=True)
    COURIERMASTER_ID = db.Column(db.Integer, nullable=True)
    cmp_code = db.Column(db.Integer, nullable=True)
    # salesinvoicedetail = db.relationship('SalesInvoiceDetail', backref='salesinvoice', lazy=True)


class SalesInvoiceDetail(db.Model):
    __tablename__ = 'salesinvoicedetail'

    def __init__(self):
        pass

    sr_no = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Sal_Inv_Dtl_Id = db.Column(db.Integer, nullable=True)
    Sal_Inv_BaleNo = db.Column(db.Integer, nullable=True)
    Sal_Inv_Pcs = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Item_Cut = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Net_Snet = db.Column(db.Unicode(255), nullable=True)
    Screen_Id = db.Column(db.Integer, nullable=True)
    Sal_Inv_Qty = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Rate = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Sal_Inv_Amount = db.Column(db.Float(precision=10, decimal_return_scale=2))
    Cmp_Code = db.Column(db.Integer, nullable=True)
    Sal_ConfNo = db.Column(db.Integer, nullable=True)
    Sales_OrderNo = db.Column(db.Unicode(255), nullable=True)
    TP = db.Column(db.Integer, nullable=True)
    Sal_LrNo = db.Column(db.Unicode(255), nullable=True)
    SerialNo = db.Column(db.Integer, nullable=True)
    Flag = db.Column(db.Integer, nullable=True)
    Sal_Inv_GreyBales = db.Column(db.Integer, nullable=True)
    Weaver_Id = db.Column(db.Integer, nullable=True)
    salInvDtlFlag = db.Column(db.Integer, nullable=True)
    Sal_Inv_ChallanNo = db.Column(db.Integer, nullable=True)
    COLOR_CHART = db.Column(db.Unicode(255), nullable=True)
    PACKINGSTYLE_ID = db.Column(db.Integer, nullable=True)
    psd_srno = db.Column(db.Integer, nullable=True)
    Sal_Inv_NetQty = db.Column(db.Float(precision=10, decimal_return_scale=2))
    FROM_PACK = db.Column(db.Unicode(255), nullable=True)
    SAL_INV_BALES = db.Column(db.Integer, nullable=True)
    Schedule = db.Column(db.Unicode(255), nullable=True)
    SchQuantity = db.Column(db.Float(precision=10, decimal_return_scale=2))
    BalesPcsMtr = db.Column(db.Unicode(255), nullable=True)
    INTYPE = db.Column(db.Unicode(255), nullable=True)
    PBALENO = db.Column(db.Unicode(255), nullable=True)
    PURCHASEINVID = db.Column(db.Integer, nullable=True)
    SAL_INV_LOTNO = db.Column(db.Unicode(255), nullable=True)
    SAL_RATEDIFF = db.Column(db.Float(precision=10, decimal_return_scale=2))
    SAL_RATEDIFFAMT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    NETRATEAMOUNT = db.Column(db.Float(precision=10, decimal_return_scale=2))
    PS_FLAG = db.Column(db.Unicode(255), nullable=True)
    GFLAG = db.Column(db.Unicode(255), nullable=True)
    DESCRIPTION = db.Column(db.Unicode(255), nullable=True)
    NETQTY = db.Column(db.Float(precision=10, decimal_return_scale=2))
    EXP_HSN = db.Column(db.Unicode(255), nullable=True)
    Item_Id = db.Column(db.Integer, nullable=True)
    Unit_Id = db.Column(db.Integer, nullable=True)
    Sal_Order_Id = db.Column(db.Integer, nullable=True)
    Sal_Inv_Id = db.Column(db.Integer, nullable=True)


class SalesInvoiceConfig(db.Model):
    __tablename__ = 'salesinvoiceconfig'

    def __init__(self):
        pass

    SrNo = db.Column(db.Integer, primary_key=True)
    Add_Less = db.Column(db.Unicode(255), nullable=True)
    Label = db.Column(db.Unicode(255), nullable=True)
    Percentage = db.Column(db.Float(precision=10, decimal_return_scale=2))
    PercentageOn = db.Column(db.Unicode(255), nullable=True)
    Type = db.Column(db.Unicode(255), nullable=True)
    LGR_ID = db.Column(db.Integer, nullable=True)
